version: "3.8"

services:

  api-despesas:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-despesas
    env_file:
      - .env
    volumes:
     - .:/api-despesas
    depends_on:
     - database
    ports:
      - 3333:3333

  database:
    image: mongo:4.4.6
    container_name: mongo-db-api-despesas
    restart: always
    ports:
      - 27017:27017